version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: dockerfile_web
        container_name: laravel_app
        ports:
            - "8000:80"
            - "5173:5173"
        depends_on:
            mysql:
                condition: service_healthy
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: chacharitas
            DB_USERNAME: root
            DB_PASSWORD: sightofthesunshine
            DB_EXTERNAL_HOST: mysql
            DB_EXTERNAL_PORT: 3306
            DB_EXTERNAL_DATABASE: location
            DB_EXTERNAL_USERNAME: root
            DB_EXTERNAL_PASSWORD: sightofthesunshine
            PHP_FPM_LISTEN: 9000
            PHP_MEMORY_LIMIT: 256M
        volumes:
            - ./:/var/www/html
            - /var/www/html/node_modules
            - /var/www/html/vendor
            - ./docker/nginx.conf:/etc/nginx/sites-available/default

    mysql:
        build:
            context: .
            dockerfile: dockerfile_db
        container_name: mysql_db
        ports:
            - "3307:3306"
        healthcheck:
            test: [ "CMD-SHELL", "mysqladmin ping -uroot -p$$MYSQL_ROOT_PASSWORD" ]
            interval: 5s
            timeout: 10s
            retries: 5
        volumes:
            - mysql_data:/var/lib/mysql
        command:
            --default-authentication-plugin=mysql_native_password
            --innodb-buffer-pool-size=512M

volumes:
    mysql_data:
